apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
    - name: task1
      taskRef:
        name: task1
      params:
        - name: secure-prop
          value: $(params.secure-prop)
